server:
  port: 8000
  ssl:
    trust-store: src/main/resources/ca_ks.jks
    trust-store-password: 12qwaszx@#WESDXC
    key-store: src/main/resources/server_ks.jks
    key-store-password: 12qwaszx@#WESDXC
    key-alias: server
    client-auth: need

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/water
    username: wind
    password: ${POSTGRES_PASS}
    dbcp2:
      driver-class-name: org.postgresql.Driver
    platform: postgres

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: com.robotad.waterserver.dialect.JsonbDialect
        temp.use_jdbc_metadata_defaults: false